### PR TITLE
Social media website - Milestone 6: Friendship v2

### PR DESCRIPTION
**Pull request by SarvarKh**
# Milestone 6: Friendships v2 
In this milestone, I have successfully:
- refactored code to make friendships with 2 rows for mutual friendship.
- added decline button for user's friend requests
- modified Readme.md file

_Note: Unit and integration tests are being implemented._

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

### Hello @SarvarKh , first of all congrats on making this far :muscle: 

### To highlight:
- Your commit messages are professional
- Good job adding readme file at this stage :+1: 

### To improve:
- [ ] Please add Unit and Integration tests,  at this stage they should be implemented ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created 
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [ ] thanks to this, we can find user friends only by user_id in friendships table 
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)  
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby) 
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [ ] in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables) 
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
- [ ] PostsController#index displays posts in a timeline (their own posts + posts from their friends) currently your app displays also posts that are not friends to the user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

Please fix the required changes and ask for another code review whenever you're ready

_**If you have any question related to the required changes feel free to comment here, or ping me on slack @GzimAsani**_

HAPPY CODING :computer: :desktop_computer:

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Sarvar Khalimov** 
Nice job with the improvement for this project :muscle:  :muscle:
Some additional changes are required before you can go ahead:

- [x] Remove commented code in app/controllers/friendships_controller.rb
- [x] Remove commented code in spec/controller/user_spec.rb
- [x] Add integration tests
- [x] Fix rubocop offenses
- [x] In your friendship model you should have a method "confirm_friend" to update the state of the friendship record and create a new record with the values of user_id and friend_id exchanged (and status equal true).
- [x] After login, the root page should only show the posts of the logged-in user and its friends.
- [x] In your user model, you should have a has many friends, using the confirmed_friendship relationship, so that way you can get all the confirmed friends of the logged-in user.
- [x] You have a typo in the decline button:


 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by SarvarKh** [comment]
### Thank you @andresporras3423 for your review :+1: 
Here is the status of your comments implementation:

1. All commented codes were **removed**.
2. Integration tests were **added**.
3. Rubocop bugs were already **fixed**, but I believe you meant to check it after changes. So, it has been **done** as well.
4. In my friendship model, there was no "confirm_friend" method, because the method with the same functionality already exists in my application_helper.rb and named as "accept_friend_request". I understand the advantage of the calling method right from the Model and have refactored the most of models' methods as per the initial comments from Gzim which triggered a chain of multiples changes in other files. Since it was taking me more than 5 days, I decided to submit. Anyway, If I must implement this feature, this is provoking another set of changes and refactoring.
5. has_many_friends method in user model using the confirmed_friendship relationship is the same as above requires significant refractory work and time.
6. Root page has been **refactored** to show only logged-in user's and its friends posts and comments.
7. Typo in decline btn has been **corrected**.

> :heavy_exclamation_mark: This is also a **reference** for the next review of a **new TSE**.

**Comment by mimipeshy** [comment]
## STATUS : APPROVED 🥳 👯 

Hello team @SarvarKh 👋🏾 👋🏾 , congratulations on making it this far in the project. Good job in implementing the required changes. You are professional in communicating what changes you have made and why you did it, keep it up 😄 . This project is therefore approved, go ahead and merge.
All the best in the next milestones

Regards
Peris Ndanu

**Pull request merged**
